
language: python
dist: bionic
branches:
  only:
    - master
    # tags with 1.1.1
    - /^v?\d+(\.\d+)*$/

python:
  - 3.7

env:
  global:
  # transifex_token
  - secure: "c52N6fBcJZwKbXBRmF1vDA9fABU3a3gmmJ6m63FoxWyDYHvk6b+jOwKU49hVlZmUM/fSfMUEG1ZgyByBmb+9U+iFJfnv2LtI79uLBSke86ufqb8M9EjCqEvQjEP1Xs7jUEhMqpJYtLy+es7mQaAkIaTu7l3970zK6xeKR7FPDi5z+nKiMfFQLpd1ACvasQ2C8s9Ymdmr4xyRZXrYjcSBN8qCKqXrgbg5gBSdYo8Qrsm81sGbIt7Ba0fOut9fWxOsS/TucYVuLC5uiMh/t3025x+4/9UcBnAecVjf7QUAmZef7njS6O+BUULGxd6QWJSnhsZwAECLjO7PhfsZPb1G5TLIYX04gmRvOzG4cgIMqyWFBNMYqfFlYfSvpb6LiRFBtMRoUV7WVU9D58YQEV6W29DA66Lho9JjiNnpUL33j/ef6Tudt1pwtSkLivAfaoeKSl/tG/4ea2jiGQjRcHLc//GiNSiHi9b6favIkt2eKPH2Ffr8rkFjwI1U2pcKWNt3C3SXG4vOyzL1uYkTzGHuaolRdMELBQEXT93ca6OHMUDngeqmB2nRH61BDv4t8lRd2Z20Ne447C6hdVz2V4yznpqSoPzLUo2T6nfLO7kkUUElg+Hxad7DGgqHwQ1Rgdv86RAhkW4k/6+HSWQB8XFHTBTw80OsDrmWbHrQ3+T8cvM="
  # github_token
  - secure: "drMd3unn7qOzHpzhwot34zBPqp35pQxro+bNbZbKgXI8cJlyP3cqXWRt7BtWQyvLQ67AyR35Jhk3I5j9NwPHcW7NmT3+n7P/6qh3E72a1E4s7XmroByTn8gRZZr8jQD7jKrJYTkCodLAFb5k5oupJp3nz0nW48Y8KbBwEAgKLVvTH8sNSY+BUrnoms2AdypifPf2fpY5R49/IkqSZE+GB/gHAAQMBHzW22FPeojZxiaQJ0oMsdBaPlaIAGAkcxNtvuSaegN0pLr6QXqcfazRENIbnr5jii5gFxLvVcC6LZGCHDIWWhe+kFCS95x7ob2hRD2alJxwcKeqqWeCSsto5dIpGKJzuyOxVr7OdhUwd+PVztsPiP+T5S3ROFSNNCZROUNwY03i/CB41GdX9LUbqdVNqFd2kO76MovHoIOz7QXlmOBGEPCndAcNKXgQ++C0Mk1Hf2VBVdf9+5wFOaQxxEyMnR62nrxyYpRikMUY3sfiDNHL2C+xTWtUfR9qYeHnHnAdUd+JmCInQcX02KvRQnNBSOd7vYxq5rDHE/eDBfmlncdT4wB48vQOwrIu6rgugRiH+4fNsa+Ea6gMiBAlnx3YhOd0ldkxxwN/IA9eCG+waDfOaNWhOp9dusseFxPnQvZjOcCpzRuuKwiKTZVo5aVcqSyI9I0q2guA80Re+Q4="

install:
  - pip install -r requirements.txt
  - sed "s/__VERSION__/${TRAVIS_TAG:-0.0.0}/g" setup.py.in > setup.py
  - python setup.py install

script:
  - qgis-plugin-ci --version
  - nose2 -v

deploy:
  on:
    tags: true
  provider: pypi
  skip_existing: true
  skip_cleanup: true
  distributions: sdist
  user:
    secure: "K/wtvhISwCuhx0Za/Q8tSDcS49cM4y0lviaE+dg2OGOhTKv2ArCQSo8ATatKzJdIiiiBkvu0hZJVnSXNTOEhVBHfhFZAfGyaj5opMlhnCPlkStWkJQjMioqQw93aNL5YYsQNmyaGsv+HwCT4u14gTH/9UO+THbYKxd1Vl2uDP3fUodvIjduC+JxeWpIkMLPnqh0aTUWXVyvuvlUg1tdqf0H/vPIitaCAzVl1VQpSQWQ/8+xYP+lzZUs7UWaUdFCQC0sLsI19wY8WCzcugX/sb50Anm2uFC0GwRmTMTiV9neGC8tjv5dICJKs9KmciCngXLND1D/1vq+z2iCI4a2rlT7nUBDaDjEowIY2qsnxT1IvUTr4bgJNLl1m+ff6VDWkiMgWV/yO2XALG3JoEnbI6Zd9CaCUBvzi9a4/eDATAXi7RBWDHMY2Z+FjA49f4ud1GRw6OR8vBPCS1mDehdKPIzD+60HvYew+YwlkzauH7y9Zb0sy861+amo+q3RTkr4ek5sdgzUhxTdlPAf12d1EwDz7hcwRNXeFOghf/Qc9H8IDb6pWj/0itCr65v4nNw5Un1u0UEuBFQmHBJHvknYPYKpWWJXCquXln559Yh15YYqnfaZklqx4b135qWSuYCBIBw8lG1MV9tRg2yxsGcC+hTXRnSGkjPmQBPdtX5PWMfs="
  password:
    secure: "nHPAVzs/jB8symXaJJTtNOzyw275wo0MR6DcM+2OPM19An1wPORhl5l5aZlrJ8R/GJu4hUEqLP1ePYGNZmrKKw++hh+vKkp7YE6U90Ryyt7cb0CIebjo/o2zp61tslpGejqKux8tWXsSQPHJWhsQx6Mk9WfXPszt4d2CtIu+tqes7XxHeM8y0qgLhRJ+wg1kc6Jbl2MCqq+qjv/VUFOQYVJXqd6tqdssC3wjxRhbzBQd1YQph0qAxQTgeJ/pJ5KDadzuWluayntnjgiNCkvjsPcIMuUG+cA3SJmOWhoB5q2tIaDq2yOa937un1OcM0Pl5EC4UtT3bQcJpy0AH6nJpUB6aBwQvD8E9qfKoSAMnCIZOgLPc0z80GFSX29s+DmAQncj8h14r9y5LU1+r7enagD+IQm5jf1GyGKTT76bgpO9Y9DswsfSnfXmpM9nJ+fPASGCxOaKrjIFNNh8HObD0dMSSwcu3hRqSTf21DKHUBWyFfkSFZ/Te6ymI59EnUjes4P8rWq8637FXo33u6YEtPpkZd6LoBY81DQvpLuIg3o2d33GP7ZBj2DTabxEEQ2pse7RitiPwGirpWO7/OcbD4Xed5oyWVVnYC3TD/USTC19pCs36BSsMHKQQahYa+KVf0S8S9seG1aqcjbbyXjFxa0lHrcV5evSllCE9MGkKfk="





