name: test qgis-plugin-ci

concurrency: testing_environment

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
  workflow_call:


jobs:
  build-python-wheel:
    name: "🐍 Python Wheel"
    uses: ./.github/workflows/wheel.yml
    secrets: inherit

  tests:
    runs-on: ubuntu-latest
    needs: [ build-python-wheel ]
    steps:
      # Not using strategy.matrix to create multiple jobs
      # as we do NOT want to test with any form of concurrency
      # to avoid 'race conditions' against Transifex

      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
          cache: "pip"
          cache-dependency-path: "requirements/*.txt"

      - name: Retrieve artifact from Python build
        uses: actions/download-artifact@v3
        with:
          name: python_wheel
          path: dist/

      - name: install
        run: python -m pip install -e .

      - name: Simple cli test
        run: qgis-plugin-ci --help

      - name: Install system requirements
        run: |
          sudo apt-get update
          sudo apt-get install qtbase5-dev qttools5-dev-tools

      - name: Tests
        env:
          tx_api_token: ${{ secrets.TRANSIFEX_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
        run: nose2 -v
